[tool.isort]
profile = "black"

[tool.black]
line-length = 88

[tool.pylint.messages_control]
disable = [
    "no-member",
    "too-many-arguments",
    "too-few-public-methods",
    "no-else-return",
    "duplicate-code",
    "too-many-branches",
    "redefined-builtin",
    "dangerous-default-value",
    "too-many-instance-attributes",
    "attribute-defined-outside-init",
]

[tool.pylint.format]
max-line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning",
	"ignore::UserWarning"
]
markers = [
    "tensorflow: mark test as tensorflow related",
    "pytorch: mark test as pytorch related",
    "jax: mark test as jax/flax related",
]
