name: Anchore Grype vulnerability scan

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - "Containerfile"
      - ".github/workflows/containers.yml"
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - "Containerfile"
      - ".github/workflows/containers.yml"
  release:
    types: [ created ]
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Containerfile --tag localbuild/testimage:latest

    - name: Run the Anchore Grype scan action
      uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
      id: scan
      with:
        image: "localbuild/testimage:latest"
        fail-build: true
        severity-cutoff: critical

    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
