name: Containers CI

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "Containerfile"
      - ".github/workflows/containers.yml"
      - ".github/workflows/container-security.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.py"
      - "Containerfile"
      - ".github/workflows/containers.yml"
      - ".github/workflows/container-security.yml"
  release:
    types: [created]

jobs:
  build_cache_buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Containerfile
          push: false
