name: "Build and Tests"

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "requirements.txt"
  pull_request:
    branches: [main]
    paths:
      - "**.py"
      - "requirements.txt"
  release:
    types: [created]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pylint src
      - name: PyTorch Tests
        run: |
          pytest -v -m pytorch
      - name: Tensorflow Tests
        run: |
          pytest -v -m tensorflow
      - name: JAX Tests
        run: |
          pytest -v -m jax
